.\" Copyright (C), 2018  Marco Maggi
.\" You may distribute this file under the terms of the GNU Free
.\" Documentation License.
.TH ccsh 1 2018-02-02
.SH NAME
ccsh \- C programs as scripts
.SH SYNOPSIS
.sp
.nf
\fBccsh\fR \fIsourcefile\fR [SCRIPT OPTIONS]\fR
.fi
.sp
.SH DESCRIPTION
.PP
A GNU Bash shell script that allows the use of C language programs as
shell scripts.

.\" ------------------------------------------------------------

.SH "SEE ALSO"
.PP
The official documentation is distributed in Texinfo format; see the
file \fBccsh\fR.

.\" ------------------------------------------------------------

.SH BUGS
.PP
See the issues at the Github project page:
.PP
.RS 4
\%http://github.com/marcomaggi/ccsh/issues
.RE

.\" ------------------------------------------------------------

.SH AUTHOR
Marco Maggi <marco.maggi-ipsu@poste.it>
.\" Local Variables:
.\" fill-column: 72
.\" default-justification: left
.\" End:
